name: sport
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_staggered_animations: ^1.0.0
  cached_network_image: ^3.2.3
  flutter_slidable: ^2.0.0 
  sqflite: ^2.2.2
  provider: ^6.0.4
  dio: ^4.0.6 
  very_good_analysis: ^3.1.0
  intl: ^0.17.0
  package_info_plus: ^3.0.2
  flappy_search_bar_fork: ^1.7.4
  circular_progress_bar_with_lines: ^0.0.5
  flutter_launcher_icons: "^0.9.0"
  flutter_svg: ^0.23.0+1
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  get_it: ^7.2.0
  auto_route: ^5.0.4
  bloc: ^8.1.1 
  connectivity_plus: ^2.1.0
  firebase_core: ^2.7.0
  firebase_remote_config: ^3.0.13
  safe_device: ^1.1.2
  webview_flutter: ^4.0.6
  onesignal_flutter: ^3.5.0

   


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 #  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
 
flutter:
  
  uses-material-design: true 
  assets:
    - assets/images/
     
  fonts:
    - family: Monto
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
    - family: Semi
      fonts:
        - asset: assets/fonts/MSemiBold.ttf 
    - family: MBold
      fonts:
        - asset: assets/fonts/MBold.ttf  
